/* fxCreateLookupTables()
   
   Automatically generate lookup tables from the specified columns
   and add corresponding foreign keys to source table via query merge
   and remove specified columns.
   lookup columns is a list of lists of format
   {{source_table_column_name1, lookup_table_name1, lookup_key_column_name1},
    {source_table_column_name2, lookup_table_name2, lookup_key_column_name2}...
   }
   Assume specified columns do not contain any nulls or error values.
   Use only on text columns.
   "(data_table as table, lookup_columns as list) as any =>"
*/

(data_table as table, lookup_columns as list) as any =>

let 
   // Create 1 lookup table
   joined_table =
      let  
         lookup_column = lookup_columns{0},
         lookup_table_name = lookup_columns{1},
         lookup_key_column_name = lookup_columns{2},
         unique_column_values = List.Distinct(Table.Column(data_table, lookup_column)),
         new_lookup_table_from_list = Table.FromList(unique_column_values, Splitter.SplitByNothing(), {lookup_column}),
         add_index_column = Table.AddIndexColumn(new_lookup_table_from_list, lookup_key_column_name,1,1),
         reorder_new_lookup_table_columns = Table.ReorderColumns(add_index_column, {lookup_key_column_name, lookup_column}),
         transform_column_types = 
            Table.TransformColumnTypes(reorder_new_lookup_table_columns, {{lookup_key_column_name, Int64.Type}, {lookup_column, type text}}),
         join_source_and_lookup_tables = Table.Join(data_table, lookup_column, transform_column_types, lookup_column, JoinKind.Inner)
      in   
         join_source_and_lookup_tables

in 
   joined_table