/*  fxSplitStringOnCharacterTransition()
    ©2026

    An alternative approach to splitting strings based on character transition
    from numeric to non-numeric or vice versa. PQ can perform splits based only on
    one of these transitions in at a time, whereas this function, and its
    predecessor can handle both in a single pass.  

    Some of the code was generated by the UI as I manually performed certain 
    operations. I then tweaked and customized the code to work with this function.

    Parameters:
                input_text - a non-zero length string
                global_grouping - if true, a list with at most two elements
                                  is returned: one for numerics and one for
                                  all other characters; by default this 
                                  parameter is false, so that the list returned
                                  may have multiple alternating sequences of 
                                  numerics and non-numerics

    Returns: the input_text as a list of groups of characters of same type (numeric or non-numeric)
	     e.g. "123ABC*76KLM$907z8" --> {"123", "ABC*", "76", "KLM$", "907", "z", "8"}


*/

(input_text as text, optional global_grouping as logical) as any =>

let
    input_ok = input_text <> "",
    input_chars = Text.ToList(input_text),
    input_table = Table.FromList(input_chars, Splitter.SplitByNothing(), {"Char"}),
    numeric_chars = {"0", "1","2","3","4","5","6","7","8","9"},
    group_mode = if List.Contains({null, false}, global_grouping) then GroupKind.Local else GroupKind.Global,
    added_is_numeric_column = Table.AddColumn(input_table, "Is Numeric", each List.Contains(numeric_chars, [Char])),
    //The following step generates an embedded table in the [Is Numeric] column of each row with structure [[Is Numeric], [Char_Group]]
    //This step groups locally, so that there can be multiple groups where [Is Numeric] is true or false, instead of just 2
    //groups,one for true, and one for false, which is what we'd have if we use the default GroupKind.Global.
    grouped_rows = Table.Group(added_is_numeric_column, {"Is Numeric"}, {{"Char_Group", each _, type table [Char=text, Is Numeric=logical]}},group_mode),
    added_chars_column = Table.AddColumn(grouped_rows, "Chars", each [Char_Group][Char]),
    display_group_chars_as_text = Table.TransformColumns(added_chars_column, {"Chars", each Text.Combine(List.Transform(_, Text.From), ""), type text}),
    removed_columns = Table.RemoveColumns(display_group_chars_as_text, {"Is Numeric", "Char_Group"}),
    chars_split_by_type = removed_columns[Chars]
    /*
        let
    Source = fxSplitStringOnCharacterTransition("ABV73578J"),
    #"Grouped Rows" = Table.Group(Source, {"Is Numeric"}, {{"Char_Group", each _, type table [Char=text, Is Numeric=logical]}},GroupKind.Local),
    #"Added Custom" = Table.AddColumn(#"Grouped Rows", "Chars", each [Char_Group][Char]),
    #"Extracted Values" = Table.TransformColumns(#"Added Custom", {"Chars", each Text.Combine(List.Transform(_, Text.From), ","), type text})
in
    #"Extracted Values"

    */

in
    chars_split_by_type